version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: scintilla
      POSTGRES_USER: scintilla
      POSTGRES_PASSWORD: scintilla_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U scintilla"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 