"""add instructions field and bot ownership to sources

Revision ID: e50222e547d6
Revises: 5abb11cc5665
Create Date: 2025-06-19 10:21:04.277421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e50222e547d6'
down_revision = '5abb11cc5665'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('instructions', sa.Text(), nullable=True))
    op.add_column('sources', sa.Column('owner_bot_id', sa.UUID(), nullable=True))
    op.alter_column('sources', 'owner_user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'sources', 'bots', ['owner_bot_id'], ['bot_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sources', type_='foreignkey')
    op.alter_column('sources', 'owner_user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('sources', 'owner_bot_id')
    op.drop_column('sources', 'instructions')
    # ### end Alembic commands ### 