"""add_is_public_field_to_sources

Revision ID: 372d38a7dbe5
Revises: d617f8eb2ccb
Create Date: 2025-06-29 20:28:01.246403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '372d38a7dbe5'
down_revision = 'd617f8eb2ccb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('bot_source_associations_bot_id_fkey'), 'bot_source_associations', type_='foreignkey')
    op.drop_constraint(op.f('bot_source_associations_source_id_fkey'), 'bot_source_associations', type_='foreignkey')
    op.create_foreign_key(None, 'bot_source_associations', 'sources', ['source_id'], ['source_id'])
    op.create_foreign_key(None, 'bot_source_associations', 'bots', ['bot_id'], ['bot_id'])
    op.drop_constraint(op.f('source_tools_source_id_fkey'), 'source_tools', type_='foreignkey')
    op.create_foreign_key(None, 'source_tools', 'sources', ['source_id'], ['source_id'])
    
    # Add is_public column with default value for existing records
    op.add_column('sources', sa.Column('is_public', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # Remove the server default after adding - new inserts will use model default
    op.alter_column('sources', 'is_public', server_default=None)
    
    op.drop_constraint(op.f('sources_owner_bot_id_fkey'), 'sources', type_='foreignkey')
    op.create_foreign_key(None, 'sources', 'bots', ['owner_bot_id'], ['bot_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sources', type_='foreignkey')
    op.create_foreign_key(op.f('sources_owner_bot_id_fkey'), 'sources', 'bots', ['owner_bot_id'], ['bot_id'], ondelete='CASCADE')
    op.drop_column('sources', 'is_public')
    op.drop_constraint(None, 'source_tools', type_='foreignkey')
    op.create_foreign_key(op.f('source_tools_source_id_fkey'), 'source_tools', 'sources', ['source_id'], ['source_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'bot_source_associations', type_='foreignkey')
    op.drop_constraint(None, 'bot_source_associations', type_='foreignkey')
    op.create_foreign_key(op.f('bot_source_associations_source_id_fkey'), 'bot_source_associations', 'sources', ['source_id'], ['source_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('bot_source_associations_bot_id_fkey'), 'bot_source_associations', 'bots', ['bot_id'], ['bot_id'], ondelete='CASCADE')
    # ### end Alembic commands ### 