"""Add MCP server and credential management

Revision ID: f682461ce5d1
Revises: fd38c526b0e2
Create Date: 2025-06-16 15:14:55.547767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f682461ce5d1'
down_revision = 'fd38c526b0e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcp_servers',
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('server_type', sa.Enum('CUSTOM_SSE', name='mcpservertype'), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('server_config', sa.JSON(), nullable=False),
    sa.Column('credential_type', sa.Enum('API_KEY_HEADER', name='credentialtype'), nullable=False),
    sa.Column('required_fields', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('server_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('bot_mcp_credentials',
    sa.Column('credential_id', sa.UUID(), nullable=False),
    sa.Column('bot_id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('credentials_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('dek_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.bot_id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['mcp_servers.server_id'], ),
    sa.PrimaryKeyConstraint('credential_id'),
    sa.UniqueConstraint('bot_id', 'server_id', name='uq_bot_server_credential')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bot_mcp_credentials')
    op.drop_table('mcp_servers')
    # ### end Alembic commands ### 