"""enhance_bot_ownership_and_source_sharing

Revision ID: 06401631d456
Revises: 0ac3d8e2a914
Create Date: 2025-06-27 15:00:48.436427

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '06401631d456'
down_revision = '0ac3d8e2a914'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Rename created_by_admin_id to created_by_user_id in bots table
    op.alter_column('bots', 'created_by_admin_id', new_column_name='created_by_user_id')
    
    # 2. Create bot_source_associations table
    op.create_table('bot_source_associations',
        sa.Column('bot_id', sa.UUID(), nullable=False),
        sa.Column('source_id', sa.UUID(), nullable=False),
        sa.Column('custom_instructions', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['bot_id'], ['bots.bot_id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('bot_id', 'source_id')
    )
    
    # Create indexes for bot_source_associations
    op.create_index('idx_bot_source_associations_bot_id', 'bot_source_associations', ['bot_id'])
    op.create_index('idx_bot_source_associations_source_id', 'bot_source_associations', ['source_id'])
    
    # 3. Create source_shares table
    op.create_table('source_shares',
        sa.Column('source_id', sa.UUID(), nullable=False),
        sa.Column('shared_with_user_id', sa.UUID(), nullable=False),
        sa.Column('granted_by_user_id', sa.UUID(), nullable=False),
        sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['granted_by_user_id'], ['users.user_id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['shared_with_user_id'], ['users.user_id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('source_id', 'shared_with_user_id')
    )
    
    # Create indexes for source_shares
    op.create_index('idx_source_shares_user_id', 'source_shares', ['shared_with_user_id'])
    op.create_index('idx_source_shares_source_id', 'source_shares', ['source_id'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop source_shares table and indexes
    op.drop_index('idx_source_shares_source_id', 'source_shares')
    op.drop_index('idx_source_shares_user_id', 'source_shares')
    op.drop_table('source_shares')
    
    # Drop bot_source_associations table and indexes
    op.drop_index('idx_bot_source_associations_source_id', 'bot_source_associations')
    op.drop_index('idx_bot_source_associations_bot_id', 'bot_source_associations')
    op.drop_table('bot_source_associations')
    
    # Rename created_by_user_id back to created_by_admin_id in bots table
    op.alter_column('bots', 'created_by_user_id', new_column_name='created_by_admin_id')
    
    # ### end Alembic commands ### 