"""add selected_bots field to messages table

Revision ID: 8e798326cd2f
Revises: eb4bae2c46af
Create Date: 2025-06-29 17:06:49.047567

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '8e798326cd2f'
down_revision = 'eb4bae2c46af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('selected_bots', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'selected_bots')
    # ### end Alembic commands ### 