"""add_user_agent_tokens_table

Revision ID: eb4bae2c46af
Revises: a8cfbdc1bb13
Create Date: 2025-06-28 10:51:08.684706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb4bae2c46af'
down_revision = 'a8cfbdc1bb13'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_agent_tokens',
    sa.Column('token_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('token_prefix', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('token_id')
    )
    op.create_index(op.f('ix_user_agent_tokens_token_hash'), 'user_agent_tokens', ['token_hash'], unique=True)
    op.drop_index(op.f('idx_bot_source_associations_bot_id'), table_name='bot_source_associations')
    op.drop_index(op.f('idx_bot_source_associations_source_id'), table_name='bot_source_associations')
    op.drop_constraint(op.f('bot_source_associations_source_id_fkey'), 'bot_source_associations', type_='foreignkey')
    op.drop_constraint(op.f('bot_source_associations_bot_id_fkey'), 'bot_source_associations', type_='foreignkey')
    op.create_foreign_key(None, 'bot_source_associations', 'bots', ['bot_id'], ['bot_id'])
    op.create_foreign_key(None, 'bot_source_associations', 'sources', ['source_id'], ['source_id'])
    op.alter_column('bots', 'created_by_user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('idx_source_shares_source_id'), table_name='source_shares')
    op.drop_index(op.f('idx_source_shares_user_id'), table_name='source_shares')
    op.drop_constraint(op.f('source_shares_source_id_fkey'), 'source_shares', type_='foreignkey')
    op.drop_constraint(op.f('source_shares_granted_by_user_id_fkey'), 'source_shares', type_='foreignkey')
    op.drop_constraint(op.f('source_shares_shared_with_user_id_fkey'), 'source_shares', type_='foreignkey')
    op.create_foreign_key(None, 'source_shares', 'sources', ['source_id'], ['source_id'])
    op.create_foreign_key(None, 'source_shares', 'users', ['granted_by_user_id'], ['user_id'])
    op.create_foreign_key(None, 'source_shares', 'users', ['shared_with_user_id'], ['user_id'])
    op.drop_constraint(op.f('source_tools_source_id_fkey'), 'source_tools', type_='foreignkey')
    op.create_foreign_key(None, 'source_tools', 'sources', ['source_id'], ['source_id'])
    op.drop_constraint(op.f('sources_owner_bot_id_fkey'), 'sources', type_='foreignkey')
    op.create_foreign_key(None, 'sources', 'bots', ['owner_bot_id'], ['bot_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sources', type_='foreignkey')
    op.create_foreign_key(op.f('sources_owner_bot_id_fkey'), 'sources', 'bots', ['owner_bot_id'], ['bot_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'source_tools', type_='foreignkey')
    op.create_foreign_key(op.f('source_tools_source_id_fkey'), 'source_tools', 'sources', ['source_id'], ['source_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'source_shares', type_='foreignkey')
    op.drop_constraint(None, 'source_shares', type_='foreignkey')
    op.drop_constraint(None, 'source_shares', type_='foreignkey')
    op.create_foreign_key(op.f('source_shares_shared_with_user_id_fkey'), 'source_shares', 'users', ['shared_with_user_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('source_shares_granted_by_user_id_fkey'), 'source_shares', 'users', ['granted_by_user_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('source_shares_source_id_fkey'), 'source_shares', 'sources', ['source_id'], ['source_id'], ondelete='CASCADE')
    op.create_index(op.f('idx_source_shares_user_id'), 'source_shares', ['shared_with_user_id'], unique=False)
    op.create_index(op.f('idx_source_shares_source_id'), 'source_shares', ['source_id'], unique=False)
    op.alter_column('bots', 'created_by_user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'bot_source_associations', type_='foreignkey')
    op.drop_constraint(None, 'bot_source_associations', type_='foreignkey')
    op.create_foreign_key(op.f('bot_source_associations_bot_id_fkey'), 'bot_source_associations', 'bots', ['bot_id'], ['bot_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('bot_source_associations_source_id_fkey'), 'bot_source_associations', 'sources', ['source_id'], ['source_id'], ondelete='CASCADE')
    op.create_index(op.f('idx_bot_source_associations_source_id'), 'bot_source_associations', ['source_id'], unique=False)
    op.create_index(op.f('idx_bot_source_associations_bot_id'), 'bot_source_associations', ['bot_id'], unique=False)
    op.drop_index(op.f('ix_user_agent_tokens_token_hash'), table_name='user_agent_tokens')
    op.drop_table('user_agent_tokens')
    # ### end Alembic commands ### 